=== rapla/rapla/src/org/rapla/components/xmlbundle/resources.dtd
<!ENTITY % text "#PCDATA">
<!ENTITY % special "br">
<!ENTITY % markup "p|b|i|strong|em|h1|h2|h3">
<!ENTITY % links "a">
<!ENTITY % link-content.mix "%text;|%markup;|%special;">
<!ENTITY % content.mix "%link-content.mix;|%links;">

<!ELEMENT resources (entry*)>
    <!ATTLIST resources default CDATA #REQUIRED> 
    <!ATTLIST resources parent CDATA #IMPLIED> 
<!ELEMENT entry ((text|icon)+)>
    <!ATTLIST entry key CDATA #REQUIRED> 
<!ELEMENT text (%content.mix;)*>
    <!ATTLIST text lang CDATA #IMPLIED> 
<!ELEMENT icon EMPTY>
    <!ATTLIST icon lang CDATA #IMPLIED> 
    <!ATTLIST icon src CDATA #REQUIRED> 
<!ELEMENT br EMPTY>
<!ELEMENT p (%content.mix;)*>
<!ELEMENT b (%content.mix;)*>
<!ELEMENT i (%content.mix;)*>
<!ELEMENT strong (%content.mix;)*>
<!ELEMENT em (%content.mix;)*>
<!ELEMENT h1 (%content.mix;)*>
<!ELEMENT h2 (%content.mix;)*>
<!ELEMENT h3 (%content.mix;)*>
<!ELEMENT a (%link-content.mix;)*>
    <!ATTLIST a href CDATA #REQUIRED>

=== rapla/rapla/src/org/rapla/plugin/notification/NotificationResources.xml
<?xml version="1.0" encoding="utf-8"?><!--*- coding: utf-8 -*-->
<!DOCTYPE resources SYSTEM "../../components/xmlbundle/resources.dtd">
<resources default="en">
  <entry key="notification_options">
    <text lang="en">Notification options</text>
    <text lang="de">Benachrichtigungs Optionen</text>
    <text lang="fr">Options de notification</text>
    <text lang="es">Notificaciones</text>
    <text lang="nl">Bericht van wijziging</text>
  </entry>
  <entry key="mail_subject">
    <text lang="en">Rapla: Allocation change of [{0}]</text>
    <text lang="de">Rapla: Reservierungsbenachrichtigung [{0}]</text>
    <text lang="fr">Rapla: Changement d''allocation pour [{0}]</text>
    <text lang="es">Rapla: Cambio de asignación para [{0}]</text>
    <text lang="nl">Rapla: Reservatie wijziging voor [{0}]</text>
  </entry>

  <entry key="mail_body">
    <text lang="en">The following allocation changes have been made by [{0}]:</text>
    <text lang="de">Die folgenden Belegungsänderungen wurden von [{0}] vorgenommen:</text>
    <text lang="fr">Les changement d'allocation suivants ont été faits:</text>
    <text lang="es">Se han hecho los siguientes cambios de asignación:</text>
    <text lang="nl">Volgende wijzigen werden uitgevoerd door [{0}]:</text>
  </entry>

  <entry key="appointment.add">
    <text lang="en">New appointment for [{0}]:</text>
    <text lang="de">Neuer Termin für [{0}]:</text>
    <text lang="fr">Nouvelle réservation pour [{0}] :</text>
    <text lang="es">Nueva cita para [{0}]</text>
    <text lang="nl">Nieuwe afspraak voor [{0}]:</text>
  </entry>

  <entry key="appointment.change">
    <text lang="en">Appointment changed for [{0}] from:</text>
    <text lang="de">Termin verändert für [{0}] von:</text>
    <text lang="fr">Changement d''horaire pour [{0}] c''était:</text>
    <text lang="es">Cambio de cita para [{0}]</text>
    <text lang="nl">Afspraak gewijzigd voor [{0}] van:</text>
  </entry>

  <entry key="appointment.remove">
    <text lang="en">Removed appointment for [{0}]:</text>
    <text lang="de">Termin für [{0}] gelöscht:</text>
    <text lang="fr">Libération de [{0}] le:</text>
    <text lang="es">Se eliminó la cita para [{0}]:</text>
    <text lang="nl">Afspraak verwijdert voor [{0}]:</text>
  </entry>
  <entry key="moved_to">
    <text lang="en">to: </text>
    <text lang="de">nach: </text>
    <text lang="fr">à:</text>
    <text lang="es">para:</text>
    <text lang="nl">naar: </text>
  </entry>  
  <entry key="modified_by">
    <text lang="en">Modified by [{0}]</text>
    <text lang="de">verändert durch [{0}]</text>
    <text lang="fr">Modifié par [{0}]</text>
    <text lang="es">Modificado por [{0}]</text>
    <text lang="nl">Gewijzigd door [{0}]</text>
  </entry>  
  <entry key="complete_reservation">
    <text lang="en">Complete event</text>
    <text lang="de">Komplette Veranstaltung</text>
    <text lang="fr">Description complète de l'évènement</text>
    <text lang="es">Descriptción completa del evento</text>
    <text lang="nl">Volledige reservatie</text>
  </entry>  

  <entry key="notify_if_owner">
    <text lang="en">Also notify on modification of own events.</text>
    <text lang="de">Benachrichtige auch bei Änderungen an eigenen Veranstaltungen.</text>
    <text lang="fr">Je veux être notifié pour les changements faits par moi-même</text>
    <text lang="es">Quiero ser notificado de los cambios hechos por mí mismo</text>
    <text lang="nl">Evenals bij een wijziging van eigen reservaties.</text>
  </entry>
  <entry key="notification.option.description">
    <text lang="en">Mail for every allocation change of the listed resources and persons</text>
    <text lang="de">Mail bei Belegungsänderung von folgenden Ressourcen und Personen</text>
    <text lang="fr">Envoit de Mail à chaque changement d'allocation des resources/personnes listées</text>
    <text lang="es">Envío de correo a cada cambio de asignación de recursos/personas listado</text>
    <text lang="nl">Stuur mij een bericht van wijziging van een reservatie met volgende Personen &amp; Middelen</text>
  </entry>
  <entry key="subscribe_notification">
    <text lang="en">Select resources for notification</text>
    <text lang="de">Wählen Sie Ressourcen für die Benachrichtigung</text>
    <text lang="fr">Sélectionnez les ressources pour la notification</text>
    <text lang="es">Seleccione los recursos para la notificación</text>
    <text lang="cs">Vyberte zdroje pro oznámení</text>
    <text lang="nl">Selecteer middelen voor kennisgeving:</text>
	<text lang="pl">Wybierz zasoby do powiadomienia</text>
	<text lang="da">Vælg ressourcer til anmeldelse</text>
  </entry>
  <entry key="disclaimer_1">
    <text lang="en">------------------------------------------------------------------------------------------------------------------------------
        This email has been sent by [{0}] </text>
    <text lang="de">------------------------------------------------------------------------------------------------------------------------------
        Diese E-mail wurde von [{0}] gesendet, </text>
    <text lang="fr"></text>
  	<text lang="es"></text> 
  	<text lang="nl">------------------------------------------------------------------------------------------------------------------------------
        Dit bericht werd verstuurd door [{0}] </text> 
  </entry>
  <entry key="disclaimer_2">
    <text lang="en">because you opted for notification on ressource/s --{0}--. If you do not want to receive this message, change your notification settings in your personal settings.
        ------------------------------------------------------------------------------------------------------------------------------</text>
    <text lang="de">weil Sie über Veränderungen der Ressource/n --{0}-- benachrichtigt werden wollten. Wenn Sie diese Nachricht nicht mehr erhalten wollen, ändern Sie die Benachrichtigungseinstellungen in ihren persönlichen Einstellungen.
        ------------------------------------------------------------------------------------------------------------------------------</text>
    <text lang="fr"></text>
  	<text lang="es"></text>  
    <text lang="nl">omdat je de optie \"bericht bij wijziging\" opteert voor het middel --{0}--. Wijzig je notificatie voorkeur als je dit bericht niet meer wenst te ontvangen.
        ------------------------------------------------------------------------------------------------------------------------------</text>
  </entry>
</resources>

=== rapla/rapla/src-resources/org/rapla/plugin/autoexport/AutoExportResources.xml
<?xml version="1.0" encoding="utf-8"?><!--*- coding: utf-8 -*-->
<!DOCTYPE resources PUBLIC "-//rapla team//DTD Language Files 1.0//" "http://rapla.sf.net/dtds/resources.dtd">
<resources default="en">
  <entry key="show_navigation">
    <text lang="en">Show navigation bar</text>
    <text lang="de">Zeige den Navigationsbalken</text>
    <text lang="fr">Affiche la barre de navigation</text>
    <text lang="es">Indicar la navegación</text>
    <text lang="nl">Navigatie balk</text>
  </entry>
  <entry key="only_allocation_info">
    <text lang="en">Only allocation information</text>
    <text lang="de">Nur Belegungsinformationen</text>
    <text lang="fr">Seulement allocation</text>
    <text lang="es">Sólo asignaciones</text>
    <text lang="cs">Moje rozvržení</text>
    <text lang="nl">Enkel bezetting</text>
    <text lang="pl">Tylko przydział zasobów</text>
	<text lang="pt">Apenas alocações</text>
  </entry>
  <entry key="webserver">
	<text lang="en">Web Server</text>
	<text lang="de">Web-Server</text>
	<text lang="fr">Serveur Web</text>
	<text lang="es">Servidor Web</text>
	<text lang="es">Webový Server</text>
	<text lang="nl">Web Server</text>
  </entry>
  <entry key="calendar_list">
    <text lang="en">Exported calendars</text>
    <text lang="de">Exportierte Kalender</text>
    <text lang="fr">Calendriers Exportés</text>
    <text lang="es">calendarios exportados</text>
    <text lang="nl">Gepubliceerde Planningen</text>
  </entry>
<!--
  <entry key="triggger_export">
  </entry>
  <entry key="export_trigggerd">
    <text lang="en">Export triggered. You probably need to wait a moment until the files are updated on the server!</text>
    <text lang="de">Export angestossen. Geben Sie der zu exportierenden Datei einen Namen!</text>
    <text lang="Fr">Export déclenché. Vous devrez probablement attendre un moment avant que les fichiers soient mis a jour sur le serveur!</text>
    <text lang="es">¡Se está exportando. Probablemente necesite esperar un momento a que se actualicen los ficheros en el servidor!</text>
  </entry>
-->
</resources>

=== rapla/rapla/src-resources/org/rapla/plugin/export2ical/Export2iCalResources.xml
<?xml version="1.0" encoding="utf-8"?><!--*- coding: utf-8 -*-->
<!DOCTYPE resources SYSTEM "../../components/xmlbundle/resources.dtd">
<resources default="en">
	<entry key="export_file_text">
		<text lang="en">Export view to iCal file</text>
		<text lang="de">Exportiere Sicht in iCal File</text>
		<text lang="fr">Exporte la vue en iCal File</text>
	</entry>
	<entry key="export_ical_text">
		<text lang="en">Publish calendar to iCal</text>
		<text lang="de">Veröffentliche Kalender nach iCal</text>
		<text lang="fr">Publier le calendrier en iCal</text>
    <text lang="es">Publicar el calendario en iCal</text>
	</entry>
	<entry key="previous_days_text">
		<text lang="en">previous days:</text>
		<text lang="de">vorhergehende Tage:</text>
		<text lang="fr">les jours précédents:</text>
	</entry>
	<entry key="subsequent_days_text">
		<text lang="en">subsequent days:</text>
		<text lang="de">darauffolgende Tage:</text>
		<text lang="fr">les jours suivants:</text>
	</entry>
	<entry key="user_interval_setting_text">
		<text lang="en">User interval setting:</text>
		<text lang="de">Benutzerspezifische Intervalleinstellung:</text>
		<text lang="fr">le paramètre d`intervalle utilisateur spécifique:</text>
	</entry>
	<entry key="created_succesfully_text">
		<text lang="en">Successfully created.</text>
		<text lang="de">Erfolgreich angelegt.</text>
		<text lang="fr">Créé avec succès.</text>
	</entry>
	<entry key="no_dates_text">
		<text lang="en">No dates available in the current view.</text>
		<text lang="de">In der aktuellen Ansicht sind keine Termine vorhanden.</text>
		<text lang="fr">Pas de dates disponibles dans la vue en cours.</text>
	</entry>
	<entry key="export_file_succesfull_text">
		<text lang="en">The iCal file has been successfully created.</text>
		<text lang="de">Die iCal Datei wurde erfolgreich erstellt.</text>
		<text lang="fr">Le fichier iCal a été créé avec succès.</text>
	</entry>
	<entry key="use_user_interval_setting_text">
		<text lang="en">use user interval setting</text>
		<text lang="de">benutzerspezifische Intervalleinstellung verwenden</text>
		<text lang="fr">utiliser le paramètre d`intervalle utilisateur spécifique:</text>
	</entry>
    <entry key="ical_export_user_settings">
        <text lang="en">ICal Export Settings</text>
        <text lang="de">ICal Export Einstellungen</text>
        <text lang="fr">ICal Export Settings</text>
    </entry>

    <entry key="participation_status">
        <text lang="en">Participation Status</text>
        <text lang="de">Teilnahme Status in Einladungen</text>
        <text lang="fr">Participation Status</text>

    </entry>

    <entry key="export_attendees_of_vevent">
        <text lang="en">Export Person Resource as Attendees</text>
        <text lang="de">Teilnehmer einer Veranstaltung exportieren</text>
        <text lang="fr">Export Person Resource as Attendees</text>
    </entry>

</resources>

=== rapla/rapla/src-resources/org/rapla/plugin/ical/ImportFromICalResources.xml
<?xml version="1.0" encoding="utf-8"?><!--*- coding: utf-8 -*-->
<!DOCTYPE resources SYSTEM "../../components/xmlbundle/resources.dtd">
<resources default="en">
    <entry key="url">
    	<text lang="en">URL</text>
    	<text lang="de">URL</text>
	</entry>
	<entry key="enter_url">
    	<text lang="en">Enter URL</text>
    	<text lang="de">URL eingeben</text>
	</entry>
	<entry key="click_for_file">
    	<text lang="en">click here to select local file</text>
    	<text lang="de">Klicken Sie hier, um eine lokale Datei auszuw√§hlen</text>
	</entry>
    <entry key="ical.import">
        <text lang="en">Import iCal Calendar</text>
        <text lang="de">Importiere iCal Kalender</text>
    </entry>


</resources>
